epochs: 200
gpus: 4 
data:
  batch_size: 256
  dataset: "data/"
  val_split: 0.2
  seed: 1337 
  nfiles: 25600
  half_prec: False
  num_workers: 4
  shuffle: True
opt:
  lr: 0.05
  b1: 0.9
  b2: 0.99
  lr_scheduler: 'reduce'
  threshold: 0.001
  patience: 3
  factor: 0.1
  loss_scale: 1.0
mod:
  M: 625
  N: 2137
  hidden: [1024, 512]
  latent: 128
es:
  patience: 5
  min_delta: 0.01